backend:
  # Choose the backend you prefer (GitHub, GitLab, BitBucket)
  # Reference: https://www.netlifycms.org/docs/authentication-backends/
  name: github
  branch: master
  repo: Druage/example_gridsome

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "posts"
    label: "Posts"
    folder: "blog"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Excerpt", name: "excerpt", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "date"}
      - {label: "Body", name: "body", widget: "markdown"}
